### ISSUE TITLE
Fix type annotation precedence issue

### ISSUE THREAD

**Issue by travisbrown** [travisbrown/dhallj#1]
The parser currently gets precedence wrong for type annotations in three situations:

* Empty lists
* `merge`
* `toMap`

These cases are some of the few places where the JavaCC grammar isn't a fairly straightforward translation of the Dhall ABNF file. I made the adjustments as a hack because I wasn't initially able to get JavaCC to handle backtracking correctly at the `expression` level for these cases. The current approach works for most cases, including everything in the parsing acceptance tests, but fails on some valid Dhall code—for example:

```scala
scala> import org.dhallj.parser.DhallParser.parse
import org.dhallj.parser.DhallParser.parse

scala> parse("[]: List Natural: Type")
org.dhallj.core.DhallException$ParsingFailure: Encountered unexpected token: ":" ":"
    at line 1, column 17.

Was expecting one of:

    <EOF>
    <WHSP>
```

Compare `dhall`:

```bash
$ dhall <<< '[]: List Natural: Type'
[] : List Natural
```

This is parsed as `[]: (List Natural: Type)`:

```bash
$ dhall encode --json <<< "[]: List Natural: Type"
[
    28,
    [
        26,
        [
            0,
            "List",
            "Natural"
        ],
        "Type"
    ]
]
$ dhall encode --json <<< "[]: ((List Natural): Type)"
[
    28,
    [
        26,
        [
            0,
            "List",
            "Natural"
        ],
        "Type"
    ]
]
```

I don't believe this bug in our parser can result in incorrect parses, only failed ones, and it's enough easy to work around:

```scala
scala> parse("[]: (List Natural: Type)").normalize.hash
res1: String = d79a2e0e14809ab2dbd2d180e60da8e129a5fb197bdd0caed57e3828402e48a9
```
Or:
```
scala> parse("[]: List (Natural: Type)").normalize.hash
res2: String = d79a2e0e14809ab2dbd2d180e60da8e129a5fb197bdd0caed57e3828402e48a9
```
Which gives the same hash as the Haskell implementation:
```bash
$ dhall hash <<< "[]: List Natural: Type"
sha256:d79a2e0e14809ab2dbd2d180e60da8e129a5fb197bdd0caed57e3828402e48a9
```

I've decided not to let this block the 0.1.0 release, but I'm planning to fix it soon.

**Comment by Nadrieril** [comment]
I think it would make sense to update the standard on this: I don't find that parse very intuitive. I would expect an error or maybe `([]: List Natural): Type`
