### ISSUE TITLE
Incorrect home page in Maven repository

### ISSUE THREAD

**Issue by simonolander** [travisbrown/dhallj#159]
The home page field in https://mvnrepository.com/artifact/org.dhallj/dhall-parser/0.7.0-M1 links to https://github.com/travisbrown/djallj, but it should link to https://github.com/travisbrown/dhallj. It looks like a simple typo.

This makes it harder to find the source and documentation for the library.

**Comment by travisbrown** [comment]
Ah, thanks for catching this. I'll fix this before the next release.

**Comment by travisbrown** [comment]
Fixed in #171.
