### ISSUE TITLE
root directory for imports

### ISSUE THREAD

**Issue by amesgen** [travisbrown/dhallj#19]
For filesystem imports, it would be nice to be able to specify the root directory (espc. as there is no easy and reliable way to change the current working dir on the JVM). `imports-mini` already supports this.

This should only involve adding e.g. `rootDirectory: Path` to `ResolutionConfig` and respecting it in `ResolveImportsVisitor`. I could create a PR for this.

**Comment by travisbrown** [comment]
In `imports-mini` you can pass in the path for the current document, which is something I needed for the tests. I'm not sure how this lines up with what @TimWSpence is working on in `imports` proper?

@amesgen Just to be sure I understand, you want to specify an alternative root directory, and not the path against which relative paths are resolved?

**Comment by amesgen** [comment]
Ah yes, my remark about `imports-mini` is wrong, I did not actually look at what `currentPath` is used for.

By "root directory" I mean the path against which relative paths are resolved, is there another meaning? Also see [rootDirectory](https://hackage.haskell.org/package/dhall-1.31.1/docs/Dhall.html#v:rootDirectory) in dhall-haskell.

**Comment by amesgen** [comment]
Ah, do you mean that one also could a "base path " for file imports with an absolute path?

**Comment by travisbrown** [comment]
@amesgen Ah, got it. Sorry, I'm not as familiar with either the spec or the Haskell implementation as @TimWSpence for things related to import resolution, but yes, I should probably change the `currentPath` in `imports-mini` to work the same as the Haskell implementation's `rootDirectory`, and we should provide the same functionality in `imports`.

**Comment by TimWSpence** [comment]
Thanks @amesgen I'm currently reworking our local imports and making sure we pass all the acceptance tests. Will look into this after that!

**Comment by TimWSpence** [comment]
@amesgen sorry I just saw you'd actually volunteered to create a PR for this! See https://github.com/travisbrown/dhallj/pull/54 - hopefully you're happy with that as an API?

**Comment by amesgen** [comment]
Yes, perfect!
