### ISSUE TITLE
YAML export escapes newlines

### ISSUE THREAD

**Issue by amesgen** [travisbrown/dhallj#27]
Using 0.1.1:
```
@ YamlConverter.toYamlString(parse(""" { a = "\n" } """).normalize()) 
res15: String = """a: \n
"""

@ JsonConverter.toCompactString(parse(""" { a = "\n" } """).normalize()) 
res16: String = "{\"a\":\"\\n\"}"
```
THe JSON output is correct, but in the YAML output, the value does not contain a newline (without quotes, \n is not an escape sequence).

**Comment by travisbrown** [comment]
Thanks, taking a look now!

**Comment by travisbrown** [comment]
I really need to just go ahead and address #11 properly. Sorry you're running into these issues—thanks for reporting them.
