### ISSUE TITLE
Parse quoted URLs correctly

### ISSUE THREAD

**Issue by TimWSpence** [travisbrown/dhallj#34]
`parse("https://example.com/foo/\"bar?baz\"?qux")` quietly catches a `java.net.URISyntaxException e` in `org.dhallj.parser.support.ParsingHelpers` and returns `null`

From a very brief look, I'd say we're parsing it correctly as a string but the `java.net.URI` constructor won't accept it. We might have to roll our own `URI` which would be _very_ annoying!

**Comment by travisbrown** [comment]
I personally don't think we _need_ to support [deprecated](https://docs.dhall-lang.org/howtos/migrations/Deprecation-of-quoted-paths-in-URLs.html) language features, although the way this currently fails is pretty bad, and we should definitely document the fact that we don't support it (if we decide not to).

(I believe the only other deprecations in the language right now are `Optional/fold` and `Optional/build`, which I did implement, but those seem a little more likely to actually be an issue for potential users.)

**Comment by TimWSpence** [comment]
Oh fantastic! Didn't realise it was deprecated. Yep, I _really_ don't want to support this if we can avoid. But agreed, it should probably not silently fail 😂
