### ISSUE TITLE
Run type-inference/success/prelude acceptance test

### ISSUE THREAD

**Issue by TimWSpence** [travisbrown/dhallj#42]
Currently ignored because it is FAR too slow. I believe this is because we repeatedly type-check sub-expressions. Probably we need to replicate Dhall-haskell's semi-semantic caching to fix this.

**Comment by travisbrown** [comment]
It's worth noting that this test does pass, it just takes a very long time. If you comment out the `ignored` override in `TypeCheckingOtherSuite` you get this:

```scala
sbt:root> slow:test
...
[info] Passed: Total 5, Failed 0, Errors 0, Passed 5
[success] Total time: 687 s (11:27), completed 19 Apr 2020, 09:34:13
```

**Comment by TimWSpence** [comment]
Resolved as of https://github.com/travisbrown/dhallj/pull/49
