### ISSUE TITLE
Run acceptance tests related to import resolution

### ISSUE THREAD

**Issue by travisbrown** [travisbrown/dhallj#8]
We're not currently running any of the `dhall-lang/tests/import` tests, or the two `type-inference` tests related to caching (`CacheImports` and `CacheImportsCanonicalize`). I don't think there's any particular reason for this now, and we have our own tests for the `imports` module that cover some of the same ground, so we should give it a try.

**Comment by TimWSpence** [comment]
Done as of https://github.com/travisbrown/dhallj/pull/32
